package com.example.hybridmusicapp.utils

import android.content.Context
import com.example.hybridmusicapp.R
import com.example.hybridmusicapp.data.model.song.NCSong

object NCSUtils {

    fun initData(context: Context): List<NCSong> {
        return listOf(
            NCSong(
                0,
                context.getString(R.string.song_no_rival),
                context.getString(R.string.artist_no_rival),
                "Dubstep / Bass",
                context.getString(R.string.desc_no_rival),
                R.drawable.no_rival,
                R.raw.no_rival
            ),
            NCSong(
                1,
                context.getString(R.string.song_mortals_remix),
                context.getString(R.string.artist_mortals_remix),
                "Dubstep / Bass",
                context.getString(R.string.desc_mortals_remix),
                R.drawable.mortals,
                R.raw.mortals_remix
            ),
            NCSong(
                2,
                context.getString(R.string.song_why_we_lose),
                context.getString(R.string.artist_why_we_lose),
                "Chill / Vocal",
                context.getString(R.string.desc_why_we_lose),
                R.drawable.why_we_lose,
                R.raw.why_we_lose
            ),
            NCSong(
                3,
                context.getString(R.string.song_blank_remix),
                context.getString(R.string.artist_blank_remix),
                "Hype Rap / EDM Rap",
                context.getString(R.string.desc_blank_remix),
                R.drawable.blank_hylo_remix,
                R.raw.blank_remix
            ),
            NCSong(
                4,
                context.getString(R.string.song_delta),
                context.getString(R.string.artist_delta),
                "EDM",
                context.getString(R.string.desc_delta),
                R.drawable.delta,
                R.raw.delta
            ),
            NCSong(
                5,
                context.getString(R.string.song_executioner),
                context.getString(R.string.artist_executioner),
                "EDM",
                context.getString(R.string.desc_executioner),
                R.drawable.executioner,
                R.raw.executioner
            ),
            NCSong(
                6,
                context.getString(R.string.song_royalty_remix),
                context.getString(R.string.artist_royalty_remix),
                "Dubstep / Bass",
                context.getString(R.string.desc_royalty_remix),
                R.drawable.royalty,
                R.raw.royalty_remix
            ),
            NCSong(
                7,
                context.getString(R.string.song_mortals_royalty_mashup),
                context.getString(R.string.artist_mortals_royalty_mashup),
                "Dubstep / Bass",
                context.getString(R.string.desc_mortals_royalty_mashup),
                R.drawable.mortals,
                R.raw.mortals_royalty
            ),
            NCSong(
                8,
                context.getString(R.string.song_symbolism),
                context.getString(R.string.artist_symbolism),
                "Other...",
                context.getString(R.string.desc_symbolism),
                R.drawable.symbolism_pt_ii,
                R.raw.symbolism
            ),
            NCSong(
                9,
                context.getString(R.string.song_sky_high_pt2),
                context.getString(R.string.artist_sky_high_pt2),
                "Other...",
                context.getString(R.string.desc_sky_high_2),
                R.drawable.sky_high_pt_ii,
                R.raw.sky_high
            ),
            NCSong(
                10,
                context.getString(R.string.song_taking_it_slow),
                context.getString(R.string.artist_taking_it_slow),
                "Other...",
                context.getString(R.string.desc_taking_it_slow),
                R.drawable.taking_it_slow,
                R.raw.taking_it_slow
            ),
            NCSong(
                11,
                context.getString(R.string.song_royalty),
                context.getString(R.string.artist_royalty),
                "Dubstep / Bass",
                context.getString(R.string.desc_royalty_original),
                R.drawable.royalty,
                R.raw.royalty
            ),
            NCSong(
                12,
                context.getString(R.string.song_on_and_on_remix),
                context.getString(R.string.artist_on_and_on_remix),
                "Chill / Vocal",
                context.getString(R.string.desc_on_and_on_remix),
                R.drawable.on_on,
                R.raw.on_on_remix
            ),
            NCSong(
                13,
                context.getString(R.string.song_lighthouse),
                context.getString(R.string.artist_lighthouse),
                "Other...",
                context.getString(R.string.desc_lighthouse),
                R.drawable.lighthouse,
                R.raw.lighthouse
            ),
            NCSong(
                14,
                context.getString(R.string.song_light_it_up),
                context.getString(R.string.artist_light_it_up),
                "Other...",
                context.getString(R.string.desc_light_it_up),
                R.drawable.light_it_up,
                R.raw.light_it_up
            ),
            NCSong(
                15,
                context.getString(R.string.song_heroes_dreams_mashup),
                context.getString(R.string.artist_heroes_dreams_mashup),
                "Other...",
                context.getString(R.string.desc_heroes_dreams_mashup),
                R.drawable.heroes_tonight_x_dreams,
                R.raw.heroes_dreams
            ),
            NCSong(
                16,
                context.getString(R.string.song_cradles),
                context.getString(R.string.artist_cradles),
                "Other...",
                context.getString(R.string.desc_cradles),
                R.drawable.cradles,
                R.raw.cradles
            ),
            NCSong(
                17,
                context.getString(R.string.song_feel_good),
                context.getString(R.string.artist_feel_good),
                "Other...",
                context.getString(R.string.desc_feel_good),
                R.drawable.feel_good,
                R.raw.feel_good
            ),
            NCSong(
                18,
                context.getString(R.string.song_live_your_life),
                context.getString(R.string.artist_live_your_life),
                "Other...",
                context.getString(R.string.desc_live_your_life),
                R.drawable.live_your_life,
                R.raw.live_your_life
            ),
            NCSong(
                19,
                context.getString(R.string.song_desperate),
                context.getString(R.string.artist_desperate),
                "Dubstep / Bass",
                context.getString(R.string.desc_desperate),
                R.drawable.desperate,
                R.raw.desperate
            ),
            NCSong(
                20,
                context.getString(R.string.song_fearless_pt2),
                context.getString(R.string.artist_fearless_pt2),
                "Other...",
                context.getString(R.string.song_fearless_pt2),
                R.drawable.fearless_pt_ii,
                R.raw.fearless
            ),
            NCSong(
                21,
                context.getString(R.string.song_running_wild),
                context.getString(R.string.artist_running_wild),
                "Epic / Cinematic",
                context.getString(R.string.desc_running_wild),
                R.drawable.running_wild,
                R.raw.running_wild
            ),
            NCSong(
                22,
                context.getString(R.string.song_be_the_one_remix),
                context.getString(R.string.artist_be_the_one_remix),
                "Other...",
                context.getString(R.string.desc_be_the_one),
                R.drawable.be_the_one_winwel_remix,
                R.raw.be_the_one
            ),
        )
    }

}